### ISSUE TITLE
Missing license file in pypi-tar-archive

### ISSUE THREAD

**Issue by Heiss** [space-physics/pyzenodo3#1]
Hey,

i tried to install your library via pip, but i get the following message:  `error: [Errno 2] No such file or directory: 'LICENSE'`. This file is missing in your tar archive on pypi.org.

Also i had to install the package `wheel` manually, so maybe you have a missing dependency, too?

Thank you and have a good day.

**Comment by scivision** [comment]
Thank you, we have recently been adding better integration tests to all our programs to proactively catch these issues, we will do it here too. Thanks

**Comment by scivision** [comment]
Thanks for noting this issue. We released v1.0.1 that modernized and fixed the packaging issues.
